function computeRealization(obj)
    import Numerics.sploewner.sploewner_quadrature;
    import Numerics.mploewner.mploewner_quadrature;
    obj.ResultData.loaded = false;
    opts = namedargs2cell(obj.options);
    switch(obj.RealizationData.ComputationalMode)
        case {Numerics.ComputationalMode.Hankel,Numerics.ComputationalMode.SPLoewner}
            [obj.ResultData.ew,obj.ResultData.rev,obj.ResultData.lev,obj.ResultData.Db,obj.ResultData.Ds,obj.ResultData.B,obj.ResultData.C,obj.ResultData.X,obj.ResultData.Sigma,obj.ResultData.Y] = sploewner_quadrature( ...
                obj.RealizationData.InterpolationData.sigma(1), ...
                obj.SampleData.Contour.z, ...
                obj.SampleData.Contour.w, ...
                obj.SampleData.Ql, ...
                obj.SampleData.Qr, ...
                obj.SampleData.Qlr, ...
                obj.RealizationData.K, ...
                obj.RealizationData.m, ...
                obj.options ...
            );
        case Numerics.ComputationalMode.MPLoewner
            [obj.ResultData.ew,obj.ResultData.rev,obj.ResultData.lev,obj.ResultData.Db,obj.ResultData.Ds,obj.ResultData.B,obj.ResultData.C,obj.ResultData.X,obj.ResultData.Sigma,obj.ResultData.Y] = mploewner_quadrature( ...
                obj.SampleData.Contour.z, ...
                obj.SampleData.Contour.w, ...
                obj.SampleData.Ql, ...
                obj.SampleData.Qr, ...
                obj.SampleData.L, ...
                obj.SampleData.R, ...
                obj.RealizationData.InterpolationData.theta, ...
                obj.RealizationData.InterpolationData.sigma, ...
                obj.RealizationData.m, ...
                opts{:} ...
            );
    end
    obj.RealizationData.loaded = true;
    obj.ResultData.ComputationalMode = obj.RealizationData.ComputationalMode;
    obj.ResultData.loaded = true;
end
